/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projeto.encapsulamento;

import java.awt.Color;

/**
 *
 * @author andre.dias.de.sena
 */
public class TelaAluno extends javax.swing.JFrame {

    Aluno aluno1 = new Aluno("123", "Andre", "ADS");

    /**
     * Creates new form TelaAluno
     */
    public TelaAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloAluno1 = new javax.swing.JLabel();
        txtNota1Aluno1 = new javax.swing.JTextField();
        txtNota2Aluno1 = new javax.swing.JTextField();
        btnVerificaAluno1 = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTituloAluno1.setBackground(new java.awt.Color(153, 102, 0));
        lblTituloAluno1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloAluno1.setText("Aluno1");

        txtNota1Aluno1.setCaretColor(new java.awt.Color(0, 102, 0));
        txtNota1Aluno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNota1Aluno1ActionPerformed(evt);
            }
        });

        txtNota2Aluno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNota2Aluno1ActionPerformed(evt);
            }
        });

        btnVerificaAluno1.setBackground(new java.awt.Color(0, 153, 255));
        btnVerificaAluno1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnVerificaAluno1.setText("Verificar Aprovação");
        btnVerificaAluno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificaAluno1ActionPerformed(evt);
            }
        });

        lblResultado.setFont(new java.awt.Font("Footlight MT Light", 1, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(241, Short.MAX_VALUE)
                .addComponent(lblResultado)
                .addGap(159, 159, 159))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(lblTituloAluno1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNota2Aluno1)
                            .addComponent(btnVerificaAluno1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNota1Aluno1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lblTituloAluno1)
                .addGap(26, 26, 26)
                .addComponent(txtNota1Aluno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtNota2Aluno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnVerificaAluno1)
                .addGap(29, 29, 29)
                .addComponent(lblResultado)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNota2Aluno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNota2Aluno1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNota2Aluno1ActionPerformed

    private void txtNota1Aluno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNota1Aluno1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNota1Aluno1ActionPerformed

    private void btnVerificaAluno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificaAluno1ActionPerformed
        // TODO add your handling code here:
        lblResultado.setText("Batata");
        Double nota1Digitada = Double.valueOf(txtNota1Aluno1.getText());
        Double nota2Digitada = Double.valueOf(txtNota2Aluno1.getText());

        aluno1.setNota1(nota1Digitada);
        aluno1.setNota2(nota2Digitada);

        if (aluno1.isAprovado()) {
            lblResultado.setText("Aluno passou! =D");
            lblResultado.setForeground(Color.green);
        } else {
            lblResultado.setText("Não passou! =(");
            lblResultado.setForeground(Color.red);

        }
    }//GEN-LAST:event_btnVerificaAluno1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerificaAluno1;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblTituloAluno1;
    private javax.swing.JTextField txtNota1Aluno1;
    private javax.swing.JTextField txtNota2Aluno1;
    // End of variables declaration//GEN-END:variables
}
